//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAF_Bootstrap.Templates {
    
    
    public partial class NestedFrameControl {
        
        /// <summary>
        /// UPToolBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPToolBar;
        
        /// <summary>
        /// ToolBar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XAF_Bootstrap.Controls.XbActionContainerHolder ToolBar;
        
        /// <summary>
        /// viewSiteControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.ViewSiteControl viewSiteControl;
    }
}
