//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace XAF_Bootstrap.Templates {
    
    
    public partial class DialogTemplate {
        
        /// <summary>
        /// UPPopupWindowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPPopupWindowControl;
        
        /// <summary>
        /// PopupWindowControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.XafPopupWindowControl PopupWindowControl;
        
        /// <summary>
        /// UPVH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPVH;
        
        /// <summary>
        /// VIC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.ViewImageControl VIC;
        
        /// <summary>
        /// VCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Controls.ViewCaptionControl VCC;
        
        /// <summary>
        /// UPSAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPSAC;
        
        /// <summary>
        /// OCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XAF_Bootstrap.Controls.XbActionContainerHolder OCC;
        
        /// <summary>
        /// SAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XAF_Bootstrap.Controls.XbActionContainerHolder SAC;
        
        /// <summary>
        /// UPEI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPEI;
        
        /// <summary>
        /// ErrorInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XAF_Bootstrap.Controls.XafBootstrapErrorInfoControl ErrorInfo;
        
        /// <summary>
        /// UPVSC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPVSC;
        
        /// <summary>
        /// VSC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XAF_Bootstrap.Controls.XafBootstrapViewSiteControl VSC;
        
        /// <summary>
        /// UPPAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.ExpressApp.Web.Templates.XafUpdatePanel UPPAC;
        
        /// <summary>
        /// PAC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XAF_Bootstrap.Controls.XbActionContainerHolder PAC;
    }
}
